### ISSUE TITLE
Require hha images 

### ISSUE THREAD

**Issue by gaosh** [liarba/scene_recognition#1]
HI,
Could you kindly provide the HHA images for easier reproduction of the results?

**Comment by liarba** [comment]
We use the Saurabh Gupta's code (https://github.com/s-gupta/rcnn-depth/blob/master/rcnn/saveHHA.m) to convert the depth images. Our converted HHA images have now been shared in https://drive.google.com/open?id=14nZI0wCu-Ki5AKHKit1dcqpBO1rN2H9p and https://drive.google.com/open?id=1TvFiLwhEmTxn8r7XNE2bpVBxoqDqLYsf.

**Comment by gaosh** [comment]
Thanks for your help.

**Comment by gaoxiaoninghit** [comment]
why the converted sun-hha lose some images，the num is 9405 instead of 10355 in origin sun-rgbd

**Comment by liarba** [comment]
We only keep categorises with more than 80 images in our experiments,
following the experimental setting of other previous works. You can find
the details in our paper.
